export const siteConfig = {
  name: "WE CORPORATE",
  description: "Professional job and internship discovery portal for verified opportunities and career growth.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://wecorporate.in",
  mainNav: [
    { title: "Find Jobs", href: "/jobs" },
    { title: "Internships", href: "/internships" },
    { title: "Career Services", href: "/career-services" },
    { title: "College Connect", href: "/connect/college" },
    { title: "Vendor Connect", href: "/connect/vendor" },
  ],
  candidateNav: [
    { title: "Dashboard", href: "/c/dashboard" },
    { title: "Profile", href: "/c/profile" },
    { title: "Resume Vault", href: "/c/resumes" },
    { title: "Applications", href: "/c/applications" },
    { title: "Saved Jobs", href: "/c/saved" },
    { title: "Consulting", href: "/c/consulting" },
    { title: "Settings", href: "/c/settings" },
  ],
  employerNav: [
    { title: "Dashboard", href: "/e/dashboard" },
    { title: "Verification", href: "/e/verification" },
    { title: "Company Profile", href: "/e/company" },
    { title: "Manage Jobs", href: "/e/jobs" },
    { title: "Post a Job", href: "/e/jobs/new" },
    { title: "Settings", href: "/e/settings" },
  ],
  adminNav: [
    { title: "Overview", href: "/admin/dashboard" },
    { title: "Employer Queue", href: "/admin/employers/queue" },
    { title: "Job Moderation", href: "/admin/jobs/moderation" },
    { title: "Curated Jobs", href: "/admin/jobs/curated" },
    { title: "Consulting Orders", href: "/admin/consulting" },
    { title: "Partnership Leads", href: "/admin/inquiries" },
    { title: "Abuse Reports", href: "/admin/reports" },
  ],
  links: {
    about: "/about",
    contact: "/contact",
    privacy: "/privacy",
    terms: "/terms",
  },
};
